feat: add editor texture manual
oasis-engine/oasis-engine.github.io pull request #145
Opened 2021-07-20 08:25 UTC by GuoLei1990

Add editor texture manual.

2021-07-22 02:37 UTC, czizzy requested changes

2021-07-22 02:37 UTC, czizzy commented on docs/editor-camera.zh-CN.md
> +点击 Camera 所在的实体**检查面板**会显示 Camera 组件的相关属性。
camera相关属性介绍一下吧，参考play canvas: https://developer.playcanvas.com/en/user-manual/packs/components/camera/，或者引擎有对应的文档链接过去也行

2021-07-22 02:37 UTC, czizzy commented on docs/editor-texture.zh-CN.md
> +![TextureToSprite](https://gw.alipayobjects.com/zos/OasisHub/16109017-fe5e-45f8-bd66-51abfcedf60e/TextureToSprite.gif)
和上面一样，texture的property也介绍一下

2021-07-22 02:42 UTC, czizzy commented on docs/editor-texture.zh-CN.md
> +![TextureToSprite](https://gw.alipayobjects.com/zos/OasisHub/16109017-fe5e-45f8-bd66-51abfcedf60e/TextureToSprite.gif)
还有纹理的压缩功能也要介绍

2021-07-28 06:51 UTC, GuoLei1990 commented on docs/editor-camera.zh-CN.md
> +点击 Camera 所在的实体**检查面板**会显示 Camera 组件的相关属性。
done

2021-07-30 06:48 UTC, czizzy approved these changes
+1

2021-08-05 12:50 UTC, zhang2333 approved these changes

2021-08-05 12:50 UTC, merged