doc: add doc for 2d
oasis-engine/oasis-engine.github.io pull request #156
Opened 2021-07-22 03:17 UTC by singlecoder

- Sprite
- Mars
- SpriteRenderer
- SpriteMask

2021-07-22 03:57 UTC, czizzy requested changes

2021-07-22 03:57 UTC, czizzy commented on docs/editor-sprite.zh-CN.md
> +![sprite-region](https://gw.alipayobjects.com/zos/OasisHub/d3c8242f-681c-4bbb-b446-7aa7276f3190/image-20210720202831351.png)
pixel per unit 属性没写

2021-08-04 03:22 UTC, czizzy approved these changes

2021-08-04 04:01 UTC, zhang2333 commented on docs/editor-sprite.zh-CN.md
> +[Sprite](${api}core/Sprite) 是 2D 图形对象，用于角色、道具、子弹以及一些其他 2D 游戏要素。这些图形是从 [Texture2D](${docs}texture-cn) 获得的。[Sprite](${api}core/Sprite) 类主要标识应用于特定Sprite的图像部分。然后 [Entity](${docs}entity-cn) 上的  [SpriteRen
Spaces around `Sprite`

2021-08-04 04:01 UTC, zhang2333 commented on docs/editor-sprite.zh-CN.md
> +对于 pivot 来说，纹理左下角为 (0, 0)，X 轴从左到右，Y 轴从下到上。在编辑器中，内置了一些常用的 pivot 快捷方式，如下：
`(0, 0)`

2021-08-04 04:01 UTC, zhang2333 commented on docs/editor-sprite.zh-CN.md
> +将 1024*1024 大小的精灵的 pixelsPerUnit 设置为 128，效果如下：
`pixelsPerUnit`

2021-08-04 04:01 UTC, zhang2333 commented on docs/editor-sprite.zh-CN.md
> +上图中一个方格代表的就是世界空间中的一个单位，我们尝试把 pixelsPerUnit 设置为 256，效果如下：
`pixelsPerUnit` `256`

2021-08-04 06:29 UTC, zhang2333 approved these changes

2021-08-04 06:36 UTC, merged