feat: 英文化Animator文档
oasis-engine/oasis-engine.github.io pull request #260
Opened 2021-08-31 02:47 UTC by luzhuang

2021-08-31 06:52 UTC, yangfengzzz requested changes

2021-08-31 06:52 UTC, yangfengzzz commented on docs/animator.md
> +You can use [AnimatioonEvent](${api}core/animation/AnimationEvent) to add events to AnimationClip. The animation event will call the specified callback function of the component you bind to the same
AnimationEvent

2021-08-31 06:52 UTC, yangfengzzz commented on docs/animator.zh-CN.md
> +你可以使用 [AnimatioonEvent](${api}core/animation/AnimationEvent) 来为AnimationClip添加事件，动画事件将在指定时间调用你在同一实体上绑定组件的指定回调函数。
AnimationEvent

2021-08-31 09:22 UTC, luzhuang commented on docs/animator.md
> +You can use [AnimatioonEvent](${api}core/animation/AnimationEvent) to add events to AnimationClip. The animation event will call the specified callback function of the component you bind to the same
fixed

2021-08-31 09:23 UTC, luzhuang commented on docs/animator.zh-CN.md
> +你可以使用 [AnimatioonEvent](${api}core/animation/AnimationEvent) 来为AnimationClip添加事件，动画事件将在指定时间调用你在同一实体上绑定组件的指定回调函数。
fixed

2021-09-02 02:32 UTC, zhuxudong approved these changes
+1

2021-09-02 02:33 UTC, merged